import TitlePage from "@/components/TitlePage";
import Link from "next/link";
import { POST } from "../page";

export function generateMetadata({ params }) {
    const post = POST.find((post) => post.slug === params.slug);
    return {
        title: post.title,
        description: "Blog " + post.title + " - Generated by create next app",
    };
}

const Slug = ({ params }) => {
    const post = POST.find((post) => post.slug === params.slug);

    return (
        <>
            <TitlePage title={post.title} />
            <p className="text-center mb-5">{post.content}</p>
            <div className="text-center">
                <Link
                    className="bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded"
                    href="/blog"
                >
                    Volver
                </Link>
            </div>
        </>
    );
};
export default Slug;
